### ISSUE TITLE
Tokenizer should produce Array[Long]

### ISSUE THREAD

**Issue by MihaiSurdeanu** [clulab/scala-transformers#10]
The tokenizer should produce Array[Long] instead of Array[Int]. ONNX expects Array[Long] as input.

See:
https://github.com/clulab/scala-transformers/blob/onnx/encoder/src/main/scala/org/clulab/scala_transformers/encoder/LoadExample.scala#L10

**Comment by kwalcock** [comment]
The hugging face tokenizer produces ints, so I would put the conversion to long somewhere in the scala code.

**Comment by MihaiSurdeanu** [comment]
Ok. I can do that. Thanks!

**Comment by kwalcock** [comment]
I was thinking something like LongTokenization(tokenization) to convert anything necessary.

**Comment by MihaiSurdeanu** [comment]
I like that. Please add it :)
