### ISSUE TITLE
Tokenizer crash

### ISSUE THREAD

**Issue by MihaiSurdeanu** [clulab/scala-transformers#21]
When using the model below, the tokenizer crashes:

```
[error] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[error] [Tokenizer] Checking /home/msurdeanu/github/scala-transformers/encoder for librust_tokenizer.so...
[error] [Tokenizer] Checking /home/msurdeanu for librust_tokenizer.so...
[error] [Tokenizer] Extracting resource librust_tokenizer.so to /tmp/librust_tokenizer-9119278600680659779.so...
[error] [Tokenizer] Loading rust interface from /tmp/librust_tokenizer-9119278600680659779.so...
[error] [Tokenizer] => create_rust_tokenizer("microsoft/deberta-v3-base")
[error] thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "Model \"microsoft/deberta-v3-base\" on the Hub doesn't have a tokenizer"', src/rust_tokenizer.rs:14:77
[error] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[error] fatal runtime error: failed to initiate panic, error 5
[error] Nonzero exit code returned from runner: 134
[error] (encoder / Compile / runMain) Nonzero exit code returned from runner: 134
[error] Total time: 49 s, completed Mar 23, 2023 12:33:13 PM
```

Is it the slash in the model name?

**Comment by kwalcock** [comment]
It doesn't work in straight Python, either.  Are you certain it is a tokenizer?

**Comment by MihaiSurdeanu** [comment]
I think it does work in Python. See:
https://github.com/clulab/scala-transformers/blob/scala/encoder/src/main/python/averager.py#L20
https://github.com/clulab/scala-transformers/blob/scala/encoder/src/main/python/configuration.py#L40

**Comment by kwalcock** [comment]
It isn't working in Python yet for me.  It would be useful to see a requirements.txt file for your computer: `pip freeze > requirements.txt`.

```
Exception has occurred: ValueError

Couldn't instantiate the backend tokenizer from one of: 
(1) a `tokenizers` library serialization file, 
(2) a slow tokenizer instance to convert or 
(3) an equivalent slow tokenizer class to instantiate and convert. 
You need to have sentencepiece installed to convert a slow tokenizer to a fast one.
  File "/home/kwa/Projects/clulab/scala-transformers-project/scala-transformers/encoder/src/main/python/clu_tokenizer.py", line 11, in get_pretrained
    tokenizer = AutoTokenizer.from_pretrained(name, model_input_names=[names.INPUT_IDS, "token_type_ids", "attention_mask"])
  File "/home/kwa/Projects/clulab/scala-transformers-project/scala-transformers/encoder/src/main/python/test_clu_tokenizer.py", line 12, in test_get_pretrained
    tokenizer = CluTokenizer.get_pretrained("microsoft/deberta-v3-base")
  File "/home/kwa/Projects/clulab/scala-transformers-project/scala-transformers/encoder/src/main/python/test_clu_tokenizer.py", line 17, in <module>
    test_get_pretrained()
ValueError: Couldn't instantiate the backend tokenizer from one of: 
(1) a `tokenizers` library serialization file, 
(2) a slow tokenizer instance to convert or 
(3) an equivalent slow tokenizer class to instantiate and convert. 
You need to have sentencepiece installed to convert a slow tokenizer to a fast one.
```
pip install sentencepiece

```
Exception has occurred: ImportError

DebertaV2Converter requires the protobuf library but it was not found in your environment. Checkout the instructions on the
installation page of its repo: https://github.com/protocolbuffers/protobuf/tree/master/python#installation and follow the ones
that match your environment. Please note that you may need to restart your runtime after installation.
  File "/home/kwa/Projects/clulab/scala-transformers-project/scala-transformers/encoder/src/main/python/clu_tokenizer.py", line 11, in get_pretrained
    tokenizer = AutoTokenizer.from_pretrained(name, model_input_names=[names.INPUT_IDS, "token_type_ids", "attention_mask"])
  File "/home/kwa/Projects/clulab/scala-transformers-project/scala-transformers/encoder/src/main/python/test_clu_tokenizer.py", line 12, in test_get_pretrained
    tokenizer = CluTokenizer.get_pretrained("microsoft/deberta-v3-base")
  File "/home/kwa/Projects/clulab/scala-transformers-project/scala-transformers/encoder/src/main/python/test_clu_tokenizer.py", line 16, in <module>
    test_get_pretrained()
ImportError: 
DebertaV2Converter requires the protobuf library but it was not found in your environment. Checkout the instructions on the
installation page of its repo: https://github.com/protocolbuffers/protobuf/tree/master/python#installation and follow the ones
that match your environment. Please note that you may need to restart your runtime after installation.
```

pip install protobuf

```
Exception has occurred: TypeError

Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
  File "/home/kwa/Projects/clulab/scala-transformers-project/scala-transformers/encoder/src/main/python/clu_tokenizer.py", line 11, in get_pretrained
    tokenizer = AutoTokenizer.from_pretrained(name, model_input_names=[names.INPUT_IDS, "token_type_ids", "attention_mask"])
  File "/home/kwa/Projects/clulab/scala-transformers-project/scala-transformers/encoder/src/main/python/test_clu_tokenizer.py", line 12, in test_get_pretrained
    tokenizer = CluTokenizer.get_pretrained("microsoft/deberta-v3-base")
  File "/home/kwa/Projects/clulab/scala-transformers-project/scala-transformers/encoder/src/main/python/test_clu_tokenizer.py", line 16, in <module>
    test_get_pretrained()
TypeError: Descriptors cannot not be created directly.
```

**Comment by MihaiSurdeanu** [comment]
Strange...
My requirements.txt (from rogue, a Linux machine) is attached.
[requirements.txt](https://github.com/clulab/scala-transformers/files/11057645/requirements.txt)

**Comment by kwalcock** [comment]
I had forgotten about this problem.  Has it magically gone away yet?

**Comment by MihaiSurdeanu** [comment]
I think it's still there... The equivalent works in python (at least on rogue), but I have to mess with the slash in the model name:
https://github.com/clulab/scala-transformers/blob/main/encoder/src/main/python/configuration.py#L41

**Comment by kwalcock** [comment]
With a new [model at artifactory](https://artifactory.clulab.org/ui/repos/tree/General/sbt-release-local/org/clulab/deberta-onnx-model/0.0.3), I get this same error:

[error] thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "Model \"microsoft/deberta-v3-base\" on the Hub doesn't have a tokenizer"', src/rust_tokenizer.rs:14:77

The code in rust_tokenizer is
```rust
let tokenizer_stack: Tokenizer = Tokenizer::from_pretrained(name, None).unwrap();
```

Is there an issue with the mapping between the name of the model and the name of the tokenizer?

**Comment by MihaiSurdeanu** [comment]
Deberta requires `add_prefix_space = False` before a tokenizer is loaded. I don't know where this is done in the refactored code. But in the old averager.py, it looked like:

```
add_prefix_space = False
  tokenizer = AutoTokenizer.from_pretrained(cf.transformer_name, model_input_names=["input_ids", "token_type_ids", "attention_mask"], add_prefix_space = add_prefix_space)
 ```

**Comment by kwalcock** [comment]
The space thing is accounted for.  I suspect that the Python layer is doing something tricky like checking hub for the tokenizer, not finding it, and then either trying an alternative name or looking somewhere else for a replacement.  I'll probably need to dig down into the code.

**Comment by MihaiSurdeanu** [comment]
Yeah... Thank you!

**Comment by kwalcock** [comment]
Notes, mostly for future me:

test_clu_tokenizer.py runs through the named, pretrained tokenizers.  For `microsoft/deberta-v3-base`, and only that one, there is a warning:
```
/home/kwa/Projects/clulab/scala-transformers-project/env/lib/python3.9/site-packages/transformers/convert_slow_tokenizer.py:446: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
```

Something is being converted to a fast tokenizer.  From [this documentation](https://huggingface.co/docs/transformers/main/main_classes/tokenizer), it sounds like a python tokenizer is being converted into a rust tokenizer:

## Tokenizer

A tokenizer is in charge of preparing the inputs for a model. The library contains tokenizers for all the models. Most of the tokenizers are available in two flavors: a full python implementation and a “Fast” implementation based on the Rust library [🤗 Tokenizers](https://github.com/huggingface/tokenizers). The “Fast” implementations allows:

* a significant speed-up in particular when doing batched tokenization and
* additional methods to map between the original string (character and words) and the token space (e.g. getting the index of the token comprising a given character or the span of characters corresponding to a given token).


Over at the [tokenizer](https://huggingface.co/docs/tokenizers/api/tokenizer) there are

* Tokenizer::from_pretrained
* Tokenizer::from_buffer
* Tokenizer::from_file
* Tokenizer::from_str

I suspect that the specification for the python tokenizer needs to be tracked down and then passed to Tokenizer via a string or buffer for lack of a pretrained, fast implementation.

**Comment by kwalcock** [comment]
See also https://github.com/huggingface/transformers/blob/main/src/transformers/convert_slow_tokenizer.py.

**Comment by MihaiSurdeanu** [comment]
Interesting!
Did you check if the outputs of the Rust and Python tokenizers for deberta are similar?
