### ISSUE TITLE
Decide how model dependencies should be specified

### ISSUE THREAD

**Issue by kwalcock** [clulab/scala-transformers#45]
Currently one of the models is specified as a library dependency.  There are a couple of apps that make use of the model.  These apps are not required in order to use the project as a library, so the model may be unnecessarily added to a project like processors.  The model needs to be removed.  There are several ways to do this:

* Put the apps in a different subproject and don't publish them, at least not as a processors dependency.
* Make them test apps that only use the model for testing.
* Filter out the dependency when the project is published.
* Remove the apps

This should be done before version 1 is released.

**Comment by MihaiSurdeanu** [comment]
I like having an apps subproject!

**Comment by kwalcock** [comment]
#46 added an apps subproject.  Clients using the encoder need to decide themselves which model to use and arrange for the corresponding library dependency to be available.
